services:
  judges_db:
    image: postgres:16
    env_file:
      - .env
    volumes:
      - judges_db_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD", "pg_isready", "-U", "${POSTGRES_USER}"]
      interval: 10s
      timeout: 5s
      retries: 5
    networks:
      - court_network

  judges_app:
    build: .
    env_file:
      - .env
    command: python manage.py runserver 0.0.0.0:8002
    volumes:
      - .:/app
      - ./logs:/app/logs
    depends_on:
      judges_db:
        condition: service_healthy
    networks:
      - court_network

volumes:
  judges_db_data:

networks:
  court_network:
    external: true