services:
  proxy:
    build: .
    ports:
      - "1408:1408"
      - "443:443"
    volumes:
      - ./static:/app/static
      - ./logs:/var/log/nginx
    networks:
      - court_network

networks:
  court_network:
    external: true