services:
  proxy:
    build: .
    ports:
      - "1408:1408"
    volumes:
      - ./static:/app/static
      - ./logs:/var/log/nginx
    networks:
      - court_network
    env_file:
      - .env

networks:
  court_network:
    external: true