services:
  proxy_nginx:
    build: .
    volumes:
      - ./logs:/var/log/nginx
      - ./static:/var/www/static
    ports:
      - "1408:1408"
      - "443:443"
    networks:
      - court_network

networks:
  court_network:
    external: true