server {
    listen 1408;
    server_name localhost;
    proxy_intercept_errors on;

    # Логирование
    access_log /var/log/nginx/access.log;
    error_log /var/log/nginx/error.log;

    # Разрешение имён через Docker DNS
    resolver 127.0.0.11 valid=30s;

    # Переменные для бэкендов
    set $parser_backend "http://parser_app:8001";
    set $judges_backend "http://judges_app:8002";
    set $datasets_backend "http://datasets_app:8003";
    set $stats_backend "http://stats_app:8004";
    set $admin_backend "http://admin_app:8005";

    # Статические файлы с кэшированием на 1 день
    location /static/ {
        alias /app/static/;
        expires 1d;
        add_header Cache-Control "public, max-age=86400";
    }

    # Главная страница
    location / {
        root /app/static;
        index index.html;
        try_files $uri $uri/ /index.html;
    }

    # Проксирование с использованием переменных
    location /parser/ {
        proxy_pass $parser_backend;
        proxy_set_header Host $host;
        proxy_set_header X-Real-IP $remote_addr;
        proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
    }

    # Login page for /judges/
    #location = /judges/ {
    #    root /app/static;
    #    try_files /login.html =404;
    #}

    location /judges/ {
    #    auth_basic "Restricted Area";
    #    auth_basic_user_file /etc/nginx/.htpasswd;
        proxy_pass $judges_backend;
        proxy_set_header Host $host;
        proxy_set_header X-Real-IP $remote_addr;
        proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
    }

    location /datasets/ {
        proxy_pass $datasets_backend;
        proxy_set_header Host $host;
        proxy_set_header X-Real-IP $remote_addr;
        proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
    }

    location /stats/ {
        proxy_pass $stats_backend;
        proxy_set_header Host $host;
        proxy_set_header X-Real-IP $remote_addr;
        proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
    }

    location /admin/ {
        proxy_pass $admin_backend;
        proxy_set_header Host $host;
        proxy_set_header X-Real-IP $remote_addr;
        proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
    }

    # Обработка ошибок
    error_page 500 502 503 504 /50x.html;
    location = /50x.html {
        root /app/static;
        internal;  # Делает страницу доступной только для обработки ошибок
    }
}