server {
    listen 1408;
    server_name localhost;

    location /static/ {
        alias /app/static/;
    }

    location / {
        root /app/static;
        index index.html;
        try_files $uri $uri/ /index.html;
    }

    location /parser/ {
        proxy_pass http://court_parser-parser_app-1:8001;
        proxy_set_header Host $host;
        proxy_set_header X-Real-IP $remote_addr;
        proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
    }

    error_page 502 503 504 /50x.html;
    location = /50x.html {
        root /app/static;
    }
}