# Generated by Django 5.1.7 on 2025-04-04 22:04

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ForumThread',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('url', models.URLField(unique=True, verbose_name='URL треда')),
                ('title', models.CharField(max_length=255, verbose_name='Заголовок')),
                ('prefix', models.CharField(blank=True, max_length=50, verbose_name='Префикс')),
                ('created_at', models.DateTimeField(verbose_name='Дата создания')),
                ('updated_at', models.DateTimeField(verbose_name='Дата обновления')),
            ],
            options={
                'verbose_name': 'Тред форума',
                'verbose_name_plural': 'Треды форума',
            },
        ),
        migrations.CreateModel(
            name='ParseProgress',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('processed_threads', models.IntegerField(default=0, verbose_name='Обработано тредов')),
                ('total_threads', models.IntegerField(default=0, verbose_name='Всего тредов')),
                ('progress', models.FloatField(default=0.0, verbose_name='Прогресс (%)')),
                ('task_id', models.CharField(blank=True, max_length=255, null=True)),
                ('status', models.CharField(default='pending', max_length=50, verbose_name='Статус')),
            ],
            options={
                'verbose_name': 'Прогресс парсинга',
                'verbose_name_plural': 'Прогресс парсинга',
            },
        ),
        migrations.CreateModel(
            name='ThreadMessage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('url', models.URLField(verbose_name='URL сообщения')),
                ('author', models.CharField(max_length=100, verbose_name='Автор')),
                ('content', models.TextField(verbose_name='Содержимое')),
                ('posted_at', models.DateTimeField(verbose_name='Дата публикации')),
                ('thread', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='parser.forumthread', verbose_name='Тред')),
            ],
            options={
                'verbose_name': 'Сообщение треда',
                'verbose_name_plural': 'Сообщения тредов',
            },
        ),
    ]
