services:
  parser_db:
    image: postgres:16
    env_file:
      - .env
    volumes:
      - parser_db_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD", "pg_isready", "-U", "${POSTGRES_USER}"]
      interval: 10s
      timeout: 5s
      retries: 5
    networks:
      - court_network

  parser_redis:
    image: redis:7.2
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 10s
      timeout: 5s
      retries: 5
    networks:
      - court_network

  parser_app:
    build: .
    env_file:
      - .env
    command: python manage.py runserver 0.0.0.0:8001
    volumes:
      - .:/app
      - ./logs:/app/logs
    depends_on:
      parser_db:
        condition: service_healthy
      parser_redis:
        condition: service_healthy
    networks:
      - court_network

  parser_celery:
    build: .
    env_file:
      - .env
    command: celery -A court_parser worker -l INFO
    volumes:
      - .:/app
      - ./logs:/app/logs
    depends_on:
      parser_db:
        condition: service_healthy
      parser_redis:
        condition: service_healthy
    networks:
      - court_network

  parser_beat:
    build: .
    env_file:
      - .env
    command: celery -A court_parser beat -l INFO --scheduler django_celery_beat.schedulers:DatabaseScheduler
    volumes:
      - .:/app
      - ./logs:/app/logs
    depends_on:
      parser_db:
        condition: service_healthy
      parser_redis:
        condition: service_healthy
    networks:
      - court_network

volumes:
  parser_db_data:

networks:
  court_network:
    external: true